/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practico5.practico5.vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.util.Map;
import javax.swing.ImageIcon;
import practico5.Contacto;
import practico5.Directorio;

/**
 *
 * @author Matias
 */
public class menu extends javax.swing.JFrame {
    
    private Directorio directorio;
    
    public menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg"
            + ""));
    Image image = icon.getImage();
    desktop = new javax.swing.JDesktopPane(){
        public void paintComponent(Graphics g){
            g.drawImage(image,0,0,getWidth(),getHeight(),this);
        }
    }
    ;
    menubar = new javax.swing.JMenuBar();
    contacto = new javax.swing.JMenu();
    Acont = new javax.swing.JMenuItem();
    Econt = new javax.swing.JMenuItem();
    Mostrar = new javax.swing.JMenuItem();
    buscar = new javax.swing.JMenu();
    Bnum = new javax.swing.JMenuItem();
    Bape = new javax.swing.JMenuItem();
    Bciu = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
    desktop.setLayout(desktopLayout);
    desktopLayout.setHorizontalGroup(
        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 453, Short.MAX_VALUE)
    );
    desktopLayout.setVerticalGroup(
        desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 440, Short.MAX_VALUE)
    );

    contacto.setText("Contactos");

    Acont.setText("Añadir Contacto");
    Acont.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AcontActionPerformed(evt);
        }
    });
    contacto.add(Acont);

    Econt.setText("Eliminar Contacto");
    Econt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            EcontActionPerformed(evt);
        }
    });
    contacto.add(Econt);

    Mostrar.setText("Mostrar contactos");
    Mostrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MostrarActionPerformed(evt);
        }
    });
    contacto.add(Mostrar);

    menubar.add(contacto);

    buscar.setText("Buscar");

    Bnum.setText("Buscar por numero");
    Bnum.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BnumActionPerformed(evt);
        }
    });
    buscar.add(Bnum);

    Bape.setText("Buscar por apellido");
    Bape.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BapeActionPerformed(evt);
        }
    });
    buscar.add(Bape);

    Bciu.setText("Buscar por ciudad");
    Bciu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BciuActionPerformed(evt);
        }
    });
    buscar.add(Bciu);

    menubar.add(buscar);

    setJMenuBar(menubar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(desktop)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(desktop)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcontActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Añadir añ = new Añadir();
        añ.setVisible(true);
        desktop.add(añ);
        desktop.moveToFront(añ);
        try {
            añ.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_AcontActionPerformed

    private void EcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcontActionPerformed
        desktop.removeAll();
        desktop.repaint();
        eliminar el = new eliminar();
        el.setVisible(true);
        desktop.add(el);
        desktop.moveToFront(el);
        try {
            el.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_EcontActionPerformed

    private void BnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnumActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Buscanumero bn = new Buscanumero();
        bn.setVisible(true);
        desktop.add(bn);
        desktop.moveToFront(bn);
        try {
            bn.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BnumActionPerformed

    private void BapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BapeActionPerformed
        desktop.removeAll();
        desktop.repaint();
        buscaapellido ba = new buscaapellido();
        ba.setVisible(true);
        desktop.add(ba);
        desktop.moveToFront(ba);
        try {
            ba.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BapeActionPerformed

    private void BciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BciuActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Buscaciudad bc = new Buscaciudad();
        bc.setVisible(true);
        desktop.add(bc);
        desktop.moveToFront(bc);
        try {
            bc.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BciuActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        desktop.removeAll();
        desktop.repaint();
        mostrar mos = new mostrar();
        mos.setVisible(true);
        desktop.add(mos);
        desktop.moveToFront(mos);
        try {
            mos.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acont;
    private javax.swing.JMenuItem Bape;
    private javax.swing.JMenuItem Bciu;
    private javax.swing.JMenuItem Bnum;
    private javax.swing.JMenuItem Econt;
    private javax.swing.JMenuItem Mostrar;
    private javax.swing.JMenu buscar;
    private javax.swing.JMenu contacto;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
