/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practico5.practico5.vistas;

/**
 *
 * @author Matias
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        contacto = new javax.swing.JMenu();
        Acont = new javax.swing.JMenuItem();
        Econt = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenu();
        Bnum = new javax.swing.JMenuItem();
        Bape = new javax.swing.JMenuItem();
        Bciu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        contacto.setText("Contactos");

        Acont.setText("Añadir Contacto");
        Acont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcontActionPerformed(evt);
            }
        });
        contacto.add(Acont);

        Econt.setText("Eliminar Contacto");
        Econt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcontActionPerformed(evt);
            }
        });
        contacto.add(Econt);

        menubar.add(contacto);

        buscar.setText("Buscar");

        Bnum.setText("Buscar por numero");
        Bnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnumActionPerformed(evt);
            }
        });
        buscar.add(Bnum);

        Bape.setText("Buscar por apellido");
        Bape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BapeActionPerformed(evt);
            }
        });
        buscar.add(Bape);

        Bciu.setText("Buscar por ciudad");
        Bciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BciuActionPerformed(evt);
            }
        });
        buscar.add(Bciu);

        menubar.add(buscar);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcontActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Añadir añ = new Añadir();
        añ.setVisible(true);
        desktop.add(añ);
        desktop.moveToFront(añ);
    }//GEN-LAST:event_AcontActionPerformed

    private void EcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcontActionPerformed
        desktop.removeAll();
        desktop.repaint();
        eliminar el = new eliminar();
        el.setVisible(true);
        desktop.add(el);
        desktop.moveToFront(el);
    }//GEN-LAST:event_EcontActionPerformed

    private void BnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnumActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Buscanumero bn = new Buscanumero();
        bn.setVisible(true);
        desktop.add(bn);
        desktop.moveToFront(bn);
    }//GEN-LAST:event_BnumActionPerformed

    private void BapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BapeActionPerformed
        desktop.removeAll();
        desktop.repaint();
        buscaapellido ba = new buscaapellido();
        ba.setVisible(true);
        desktop.add(ba);
        desktop.moveToFront(ba);
    }//GEN-LAST:event_BapeActionPerformed

    private void BciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BciuActionPerformed
        desktop.removeAll();
        desktop.repaint();
        Buscaciudad bc = new Buscaciudad();
        bc.setVisible(true);
        desktop.add(bc);
        desktop.moveToFront(bc);
    }//GEN-LAST:event_BciuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acont;
    private javax.swing.JMenuItem Bape;
    private javax.swing.JMenuItem Bciu;
    private javax.swing.JMenuItem Bnum;
    private javax.swing.JMenuItem Econt;
    private javax.swing.JMenu buscar;
    private javax.swing.JMenu contacto;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
