/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practico5.practico5.vistas;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultListModel;
import practico5.Contacto;
import practico5.Directorio;

/**
 *
 * @author Matias
 */
public class mostrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form mostrar
     */
    public mostrar() {
        initComponents();
        cargar();
    }
    public void cargar(){
        for (Map.Entry<Long, Contacto> en : Directorio.listaContacto.entrySet()) {
            Long key = en.getKey();
            Contacto val = en.getValue();
            modelo.addElement(val);
            modelo.addElement("TEL:" + key);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        modelo = new DefaultListModel();
        lista = new javax.swing.JList<>();

        lista.setModel(modelo);
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    public DefaultListModel modelo;
    // End of variables declaration//GEN-END:variables
}
